# Generated by Django 3.1.3 on 2020-11-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('learned', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=120)),
            ],
        ),
    ]
